-- Xiaohe order recycle bin and audit log.
alter table public.orders
  add column if not exists deleted_at timestamptz,
  add column if not exists deleted_by uuid references auth.users(id) on delete set null;

create index if not exists orders_active_created_at_idx on public.orders (created_at desc) where deleted_at is null;
create index if not exists orders_deleted_at_idx on public.orders (deleted_at desc) where deleted_at is not null;
create index if not exists orders_deleted_by_idx on public.orders (deleted_by) where deleted_by is not null;

create table if not exists public.order_audit_logs (
  id bigint generated by default as identity primary key,
  order_id text not null,
  action text not null check (action in ('trash', 'restore', 'permanent_delete')),
  actor_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists order_audit_logs_order_created_idx on public.order_audit_logs (order_id, created_at desc);
create index if not exists order_audit_logs_actor_id_idx on public.order_audit_logs (actor_id) where actor_id is not null;
alter table public.order_audit_logs enable row level security;

drop policy if exists "admins read order audit logs" on public.order_audit_logs;
create policy "admins read order audit logs" on public.order_audit_logs for select to authenticated
using (exists (select 1 from public.admin_users a where a.user_id = (select auth.uid())));

create or replace function public.log_order_recycle_action()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  if tg_op = 'DELETE' then
    insert into public.order_audit_logs(order_id, action, actor_id)
    values (old.id, 'permanent_delete', (select auth.uid()));
    return old;
  end if;
  if old.deleted_at is null and new.deleted_at is not null then
    insert into public.order_audit_logs(order_id, action, actor_id)
    values (new.id, 'trash', (select auth.uid()));
  elsif old.deleted_at is not null and new.deleted_at is null then
    insert into public.order_audit_logs(order_id, action, actor_id)
    values (new.id, 'restore', (select auth.uid()));
  end if;
  return new;
end;
$$;

revoke all on function public.log_order_recycle_action() from public, anon, authenticated;
drop trigger if exists orders_recycle_audit_trigger on public.orders;
create trigger orders_recycle_audit_trigger after update of deleted_at or delete on public.orders
for each row execute function public.log_order_recycle_action();
